#server.servlet.context-path=/api
#server.address=192.168.1.107
server:
  ssl:
    key-store: ./src/main/resources/xll.keystore
    key-store-password: 123456
    key-store-type: PKCS12
  port: 8433

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mobile_attendance_schema?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  cache:
    redis:
      time-to-live: 60m
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_empty
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted

logging:
  level:
    com.as.attendance_springboot.mapper: DEBUG
  file:
    path: logs/info.log
    name: logs/info.log
mpp:
  entityBasePath: com.as.attendance_springboot.model
